name: CD

on:
  push:
    branches:
      - master

env:
  SHA: ${{ github.SHA }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2

      - uses: webfactory/ssh-agent@cb8b21017acfd319f0f4eb320ae495f22c36d0a7
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}

      - name: Install dependencies
        run: |
          make install

      - name: Run deployment
        run: |
          make deploy
